### ISSUE TITLE
Question about the equation on  the paper

### ISSUE THREAD

**Issue by leekum2018** [anon294384/DiffuseIT#10]
Hello, thanks for your great work! Here I have a question regarding equation 9 on the paper. Is it x_(t-1) instead of x_(t-1) in the second term of right hand side, i.e., 
![Screenshot 2023-05-25 at 12 52 13](https://github.com/cyclomon/DiffuseIT/assets/48008881/75a96ced-15bd-4a9e-be8a-e150190a5f38)
Thank you!

**Comment by cyclomon** [comment]
Hi, I followed the previous work of Manifold Constraint Gradient(MCG) paper,
Improving Diffusion Models for Inverse Problems using Manifold Constraints (NeurIPS 2022).

In the secodn term, x_t is correct.
