### ISSUE TITLE
How to train a custom model

### ISSUE THREAD

**Issue by OmSDeshmukh** [anon294384/DiffuseIT#13]
Hey, I tried your pre-trained models. They are really good. Do you have code to train a custom model on a different dataset from the ones mentioned in the Readme file.

**Comment by cyclomon** [comment]
Hi, the pre-trained model I uploaded is brought from ADM model (Diffusion Models Beat GANs on Image Synthesis, [https://github.com/openai/guided-diffusion](https://github.com/openai/guided-diffusion) ) . You can train the new model using the same protocol from ADM.

**Comment by OmSDeshmukh** [comment]
Thanks!
