### ISSUE TITLE
Question on FFHQ setup.

### ISSUE THREAD

**Issue by WonwoongCho** [anon294384/DiffuseIT#2]
Hello, thank you for sharing your awesome project :)
I have a question on the hyperparameters that you used for Figure 8 in your paper.

I guess the command would look like this:
python main.py -I "source_image"  --output_path "output_path" 
-tg "target_image" --use_range_restart --diff_iter 100 --timestep_respacing 200 --skip_timesteps 80 
--use_colormatch --use_noise_aug_all --use_ffhq

Please correct me if I am wrong.
Thank you for reading my question!

Minor thing to note:
You may want to add information about the pretrained arc face model to the README file.

**Comment by anon294384** [comment]
Hi, yes this is correct command.
I will include arcface model checkpoint.
