### ISSUE TITLE
configurations for reproducing Figure 1

### ISSUE THREAD

**Issue by roomo7time** [anon294384/DiffuseIT#5]
First of all, thank you for your great work!

I'd like to know the exact configurations for reproducing the figure 1. It would be great if you can provide the details.

Thanks!

**Comment by Yamm01** [comment]
Thank you for this  being public . I find that you are using grayscale images. I would like to know how to convert grayscale images to rgb images.

**Comment by cyclomon** [comment]
Hi, we used the default setting elaborated in our paper.
Since it is based on DDPM, reproducing exact same would not be possible due to stochastic diversity.
