### ISSUE TITLE
No results generated

### ISSUE THREAD

**Issue by Whp888** [anon294384/DiffuseIT#8]
Hello,when I use the second training method（Image-guided Image translation to train）. No pictures are generated in the folder generated after training.
The nomenclature I use is as follows: python main.py -i "input_example/source.jpg"  --output_path "./outputs/output_reptile3" -tg "input_example/leopard.jpg" --use_range_restart --diff_iter 100 --timestep_respacing 200 --skip_timesteps 80 
 Why? What should I do?  Thank you very much!!

**Comment by cyclomon** [comment]
Hi, in the source code or image-guided translation, the images are saved when setting --use_colormatch.

I will revise the code.
